### ISSUE TITLE
Cannot install in Ubuntu 16.04 LTS

### ISSUE THREAD

**Issue by alothings** [JoseExposito/touchegg#270]
The release version of Ubuntu 16.04 LTS is already out, so it's normal to run into issues, which happened in this case.
After following the instructions, I run into a problem when running the command 'make'.
The following error is thrown: 

...

```
Xtst -lXext -lQtXml -L/home/alonso/anaconda2/lib -lQtGui -L/usr/X11R6/lib -lQtCore -lpthread 
//lib/x86_64-linux-gnu/libsystemd.so.0: undefined reference to `lzma_stream_decoder@XZ_5.0'
//lib/x86_64-linux-gnu/libsystemd.so.0: undefined reference to `lzma_end@XZ_5.0'
//lib/x86_64-linux-gnu/libsystemd.so.0: undefined reference to `lzma_code@XZ_5.0'
collect2: error: ld returned 1 exit status
Makefile:176: recipe for target 'touchegg' failed
make: *** [touchegg] Error 1
```

Any suggestions?

**Comment by JoseExposito** [comment]
Hi Alonso,

I didn't have the opportunity to test 16.04 yet, but I hope this patch @chrmod submitted will fix the issue for you: https://github.com/JoseExposito/touchegg/pull/266

Just clone his repo ($ git clone https://github.com/chrmod/touchegg.git) and compile the source code as usual.

As tomorrow is Ubuntu 16.04 will be officially released, I'd like to do a big refactor of the source code to adapt it to the latest Ubuntu version.

Please let me know if that worked for you,
Jose

**Comment by alothings** [comment]
Hi Jose,

Thanks for the response. I'm getting a similar error with chrmod's version. 

```
`alonso@ThinkPad:~/Apps$ make
g++ -c -pipe -O2 -Wall -W -D_REENTRANT -DQT_NO_DEBUG -DQT_GUI_LIB -DQT_CORE_LIB -DQT_SHARED -I../anaconda2/mkspecs/linux-g++ -I. -I../anaconda2/include/QtCore -I../anaconda2/include/QtGui -I../anaconda2/include -I. -Itouchegg/src/touchegg -Itouchegg/src/touchegg/config -Itouchegg/src/touchegg/windows -Ipycharm-community-2016.1.2/helpers/pydev/pydevd_attach_to_process/dll -Itouchegg/src/touchegg/actions/factory -Itouchegg/src/touchegg/actions/implementation -Itouchegg/src/touchegg/actions/types -Itouchegg/src/touchegg/gestures/collector -Itouchegg/src/touchegg/gestures/factory -Itouchegg/src/touchegg/gestures/handler -Itouchegg/src/touchegg/gestures/implementation -Itouchegg/src/touchegg/gestures/types -I. -o Main.o touchegg/src/touchegg/Main.cpp
touchegg/src/touchegg/Main.cpp:20:35: fatal error: src/touchegg/Touchegg.h: No such file or directory
compilation terminated.
Makefile:301: recipe for target 'Main.o' failed
make: *** [Main.o] Error 1
`
```

Does it matter where I clone the directory? I'm cloning it and running all the commands from ~/Apps/

**Comment by JoseExposito** [comment]
You need to run then from the Touchegg folder, for  example:

```
$ git clone URL
$ cd touchegg
$ qmake
$ make
$ sudo make install
```

**Comment by alothings** [comment]
Following those instructions, after I clone URL.
Then run qmake, which gives me

`   Project MESSAGE: Warning: unknown QT: x11extras
`

But it does create a Makefile.
Then when I run make I get a similar error message as before:

```
`In file included from src/touchegg/config/Config.h:24:0,
                       from src/touchegg/config/Config.cpp:21:

./src/touchegg/util/Include.h:26:25: fatal error: QtWidgets: No such file or directory

compilation terminated.

Makefile:389: recipe for target 'Config.o' failed

make: *** [Config.o] Error 1`
```

**Comment by JoseExposito** [comment]
Try to:

```
$ sudo apt-get install libqt5x11extras5-dev
```

The make error (QtWidgets: No such file or directory) happens with the official code or with the pull request I commented you?

Jose

**Comment by alothings** [comment]
I just checked my Qt version. I have Qt version 4.8.7 which is the current default used by Anaconda.
I modified Include.h to what you had before, because @chrmod modifications are for Qt5.

```
#include <QtGui>
#include <QtGui/QX11Info>
```


And run into the same problem as my first comment.

**Comment by alothings** [comment]
The QtWidgets: Not found occurs with the new version, because that's for Qt version 5, and I'm using 4.8.

Here is what I read: http://stackoverflow.com/questions/23979798/include-qtwidgets-not-working-in-qt-4

**Comment by deecewan** [comment]
did you get thing working in 16.04, alothings?

**Comment by alothings** [comment]
@deecewan Yes, sorry for the late response. I updated to 16.10, and installed touchegg from apt, and touchegg-cge following the instructions. Almost everything works except the PINCH gesture
